# Generated by Django 6.0.5 on 2026-05-08 15:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('users', '0002_counselor'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerSupportUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='peer_supporters', to='core.student')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='peer_support_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Peer Support User',
                'verbose_name_plural': 'Peer Support Users',
            },
        ),
    ]
