# Generated by Django 6.0.5 on 2026-06-02 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_peersupportsession'),
        ('users', '0003_peersupportuser'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='peersupportuser',
            name='student',
        ),
        migrations.AddField(
            model_name='peersupportuser',
            name='students',
            field=models.ManyToManyField(blank=True, related_name='peer_supporters', to='core.student'),
        ),
    ]
