services:
  db:
    image: postgres:17
    container_name: aac_tim4_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: aac_tim4
      POSTGRES_USER: aac_user
      POSTGRES_PASSWORD: aac_password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: