# Generated by Django 6.0.5 on 2026-05-11 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='gender',
            field=models.CharField(blank=True, choices=[('M', 'Muško'), ('F', 'Žensko'), ('O', 'Ostalo')], max_length=1),
        ),
    ]
