# Generated by Django 6.0.5 on 2026-05-12 18:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_student_is_active'),
        ('users', '0003_peersupportuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField()),
                ('type', models.CharField(choices=[('initial', 'Inicijalni'), ('follow_up', 'Praćenje'), ('other', 'Ostalo')], default='follow_up', max_length=20)),
                ('format', models.CharField(choices=[('in_person', 'Uživo'), ('phone', 'Telefonski'), ('video', 'Video poziv')], default='in_person', max_length=20)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('counselor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='meetings', to='users.counselor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='meetings', to='core.student')),
            ],
            options={
                'verbose_name': 'Meeting',
                'verbose_name_plural': 'Meetings',
                'ordering': ['-date_time'],
            },
        ),
    ]
