# Generated by Django 6.0.5 on 2026-05-13 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_meeting'),
    ]

    operations = [
        migrations.CreateModel(
            name='Guideline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('content', models.TextField()),
                ('disabilities', models.ManyToManyField(related_name='guidelines', to='core.disability')),
            ],
            options={
                'verbose_name': 'Guideline',
                'verbose_name_plural': 'Guidelines',
                'ordering': ['title'],
            },
        ),
    ]
