# Generated by Django 6.0.5 on 2026-05-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_guideline'),
    ]

    operations = [
        migrations.AlterField(
            model_name='accommodation',
            name='status',
            field=models.CharField(choices=[('proposed', 'Predložena'), ('approved', 'Odobrena'), ('active', 'Aktivna'), ('expired', 'Istekla')], default='proposed', max_length=20),
        ),
        migrations.AlterField(
            model_name='accommodation',
            name='type',
            field=models.CharField(choices=[('permanent', 'Trajna'), ('temporary', 'Privremena')], default='permanent', max_length=20),
        ),
        migrations.AlterField(
            model_name='disability',
            name='type',
            field=models.CharField(choices=[('permanent', 'Trajna'), ('temporary', 'Privremena')], default='permanent', max_length=20),
        ),
    ]
