# Generated by Django 6.0.5 on 2026-06-02 16:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_accommodation_status_alter_accommodation_type_and_more'),
        ('users', '0003_peersupportuser'),
    ]

    operations = [
        migrations.CreateModel(
            name='PeerSupportSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('duration_minutes', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True)),
                ('peer_support_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='users.peersupportuser')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='peer_support_sessions', to='core.student')),
            ],
            options={
                'verbose_name': 'Peer Support Session',
                'verbose_name_plural': 'Peer Support Sessions',
                'ordering': ['-date'],
            },
        ),
    ]
